### ISSUE TITLE
Add in flickr attribution message in bottom-right hand corner

### ISSUE THREAD

**Issue by justin0022** [justin0022/lfs-tlef-flickr#22]
'This product uses the Flickr API but is not endorsed or certified by Flickr.'

**Comment by patricklinpl** [comment]
[Added subtle Flickr Attribution](https://github.com/justin0022/lfs-tlef-flickr/commit/25e83dc9b5de370a11389e10f5a7bfc73ba8433b)

**Comment by patricklinpl** [comment]
![screen shot 2017-07-28 at 3 02 45 pm](https://user-images.githubusercontent.com/15319206/28737980-d94152ae-73a5-11e7-80ab-e5d66070302d.png)
@justin0022
